version: '3.1'
services:
  dev:
    build: .
    container_name: soatmspayment
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    environment:
      CONN_STR: mongodb://soatuser:soatpassword@mongo:27017/
      RABBIT_DIAL_STR: amqp://guest:guest@rabbitmq:5672/
      RABBIT_EXCHANGE: ex_producao
      RABBIT_KEY: soatkey
      MP_ACCESS_TOKEN: 'TEST-2880691368345476-012710-4ebe6a834ba55ea8fb688f53afb3fae5-1547697548'
      MP_WEBHOOK_NOTIFICATION: 'https://webhook.site/95c442bb-780b-421f-a23c-5d6b5788edf6'
      ENVIRONMENT: PROD
    ports:
      - 8001:8001
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soatuser
      MONGO_INITDB_ROOT_PASSWORD: soatpassword
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: soatuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: soatpassword
      ME_CONFIG_MONGODB_URL: mongodb://soatuser:soatpassword@mongo:27017/
  rabbitmq:
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
  ms-orders:
    image: mateuspanda/ms-orders:2
    container_name: ms-orders
    ports:
      - "8181:8080"
    depends_on:
      - db-servicos
      - rabbitmq
  db-servicos:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_servicos_data:/var/lib/mysql
      - .docker-data/migrations:/docker-entrypoint-initdb.d
  mongo-production:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  ms-production:
    restart: always
    image: mateuspanda/ms-production:1
    container_name: ms-production
    environment:
      ConnectionStrings_MongoConnection: "mongodb://root:root@my-mongo-production:27018"
      RabbitMqConfig__Host: "rabbitmq"
      RabbitMqConfig__Port: "5672"
      RabbitMqConfig__User: "guest"
      RabbitMqConfig__Password: "guest"
      RabbitMqConfig__VirtualHost: /
    ports:
      - "5100:80"
    depends_on:
      - mongo-production
      - rabbitmq
      - dev
volumes:
  db_servicos_data: