version: '3.1'
services:
  dev:
    build: .
    container_name: soatmspayment
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    environment:
      CONN_STR: mongodb://soatuser:soatpassword@mongo:27017/
      RABBIT_DIAL_STR: amqp://soatuser:soatpassword@rabbitmq:5672/
      RABBIT_EXCHANGE: amq.direct
      RABBIT_KEY: soatkey
      MP_ACCESS_TOKEN: soat-access-token
      MP_WEBHOOK_NOTIFICATION: soat-webhook-notification
      ENVIRONMENT: PROD
    ports:
      - 8001:8001
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soatuser
      MONGO_INITDB_ROOT_PASSWORD: soatpassword
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: soatuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: soatpassword
      ME_CONFIG_MONGODB_URL: mongodb://soatuser:soatpassword@mongo:27017/
  rabbitmq:
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: soatuser
      RABBITMQ_DEFAULT_PASS: soatpassword
      RABBITMQ_DEFAULT_VHOST: /
networks:
  default:
    driver: bridge