version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soatuser
      MONGO_INITDB_ROOT_PASSWORD: soatpassword
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: soatuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: soatpassword
      ME_CONFIG_MONGODB_URL: mongodb://soatuser:soatpassword@mongo:27017/
  rabbitmq:
    image: rabbitmq:3.12.8-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
  ms-orders:
    image: mateuspanda/ms-orders:2
    container_name: ms-orders
    ports:
      - "8181:8080"
    depends_on:
      - db-servicos
      - rabbitmq
  db-servicos:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_servicos_data:/var/lib/mysql
      - .docker-data/migrations:/docker-entrypoint-initdb.d
volumes:
  db_servicos_data: