apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deploy
spec:
  template:
    metadata:
      name: rabbitmq-deploy
      labels:
        app: rabbitmq-deploy
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.8-management
          ports:
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
  selector:
    matchLabels:
      app: rabbitmq-deploy