apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  CONN_STR: bW9uZ29kYjovL3NvYXR1c2VyOnNvYXRwYXNzd29yZEBzb2F0ZGItc3ZjOjI3MDE3Lw==
  RABBIT_DIAL_STR: IGFtcXA6Ly9zb2F0dXNlcjpzb2F0cGFzc3dvcmRAc29hdHF1ZXVlOjU2NzIv
  MP_ACCESS_TOKEN: VEVTVC0yODgwNjkxMzY4MzQ1NDc2LTAxMjcxMC00ZWJlNmE4MzRiYTU1ZWE4ZmI2ODhmNTNhZmIzZmFlNS0xNTQ3Njk3NTQ4
  MP_WEBHOOK_NOTIFICATION: aHR0cHM6Ly93ZWJob29rLnNpdGUvOTVjNDQyYmItNzgwYi00MjFmLWEyM2MtNWQ2YjU3ODhlZGY2
